_target_: napc.cctv_dataset.DataModule
defaults:
- ds_conf@train_ds_conf: cctv_data_vd2_train
- ds_conf@test_ds_conf: cctv_data_vd2
- ds_conf@val_ds_conf: cctv_data_vd2
- _datamodule_settings
napci_path: /net/vericon/napc_data/cctv/cctv_passenger_bb_sel_350_100_25_2.csv