_target_: napc.model.NAPC
defaults:
- base_model
- input: conv_baseline
- intermediate: xlstm
- output: dense

# Overwrite the embedding_dim for all components
input:
  embedding_dim: 64
intermediate:
  config:
    embedding_dim: 64
    num_blocks: 4
    slstm_at:
      - 0
      - 1
      - 2
      - 3 
    slstm_block:
      slstm:
        backend: cuda
output:
  embedding_dim: 64
