_target_: napc.model.NAPC
defaults:
- base_model
- input: conv_baseline
- output: dense

# Overwrite the embedding_dim for all components
input:
  embedding_dim: 128
output:
  embedding_dim: 128
intermediate:
  _target_: napc.model.LSTMModuleFast
  num_layers: 12
  embedding_dim: 128
  input_dim: 128
  dropout_rate: 0.2