_target_: napc.model.NAPC
defaults:
- base_model
- input: dense_baseline
- intermediate: mlstm
- output: dense

# Overwrite the embedding_dim for all components
input:
  embedding_dim: 64
intermediate:
  config:
    embedding_dim: 64
    num_blocks: 6
output:
  embedding_dim: 64
